services:
  php:
    build:
      context: .
      target: dev
    container_name: php_server
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://hype_user:hype_password@db:3306/hype_distributor"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
    user: "1000:1000" 

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: 'mysql/mysql-server:8.0'
    container_name: db_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hype_distributor
      MYSQL_USER: hype_user
      MYSQL_PASSWORD: hype_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  php_app:
